"""empty message

Revision ID: 6d02d3d6c9ee
Revises: be48cfde93ed
Create Date: 2021-09-28 19:25:15.336342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d02d3d6c9ee'
down_revision = 'be48cfde93ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_connections', sa.Column('id', sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_connections', 'id')
    # ### end Alembic commands ###
