"""add connection between user and hearts

Revision ID: c20d51f045b8
Revises: 1d344ca35efe
Create Date: 2021-09-27 15:20:20.703293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20d51f045b8'
down_revision = '1d344ca35efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hearts', sa.Column('connector_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hearts', 'users', ['connector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hearts', type_='foreignkey')
    op.drop_column('hearts', 'connector_id')
    # ### end Alembic commands ###
