"""empty message

Revision ID: d99fa9e226c7
Revises: be48cfde93ed
Create Date: 2021-09-28 19:56:05.506498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99fa9e226c7'
down_revision = 'be48cfde93ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_connections', sa.Column('id', sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False))
    op.create_unique_constraint(None, 'user_connections', ['id'])
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['user_connections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_connections', type_='unique')
    op.drop_column('user_connections', 'id')
    op.drop_table('messages')
    # ### end Alembic commands ###
