"""added profile and display name columns to user model

Revision ID: 0db30457d33b
Revises: ffdc0a98111c
Create Date: 2021-09-21 15:20:31.496684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0db30457d33b'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.String(length=40), nullable=False))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###
