"""empty message

Revision ID: dfd00ae01572
Revises: 0db30457d33b
Create Date: 2021-09-22 11:39:18.194821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd00ae01572'
down_revision = '0db30457d33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hearts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('open', sa.Boolean(), nullable=False),
    sa.Column('time_to_live', sa.Integer(), nullable=False),
    sa.Column('content_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hearts')
    # ### end Alembic commands ###
