"""empty message

Revision ID: be48cfde93ed
Revises: c20d51f045b8
Create Date: 2021-09-28 13:29:50.834073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be48cfde93ed'
down_revision = 'c20d51f045b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hearts', sa.Column('grand_reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hearts', 'replies', ['grand_reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hearts', type_='foreignkey')
    op.drop_column('hearts', 'grand_reply_id')
    # ### end Alembic commands ###
